const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    card: '#FFFFFF',
    cardAlt: '#F5F5F5',
    border: '#E0E0E0',
    secondaryText: '#666666',
    input: '#FFFFFF',
    accent: '#007AFF',
    accentText: '#FFFFFF',
    activeCard: '#E6F3FF',
    activeBorder: '#0066CC',
    activeText: '#0066CC',
    buttonDisabled: '#A0A0A0',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    card: '#1E2124',
    cardAlt: '#252A2E',
    border: '#2E3336',
    secondaryText: '#9BA1A6',
    input: '#252A2E',
    accent: '#007AFF',
    accentText: '#FFFFFF',
    activeCard: '#1A2C40',
    activeBorder: '#4A9EFF',
    activeText: '#4A9EFF',
    buttonDisabled: '#555555',
  },
};
