import { StyleSheet } from "react-native";

import { ms, s } from "@/utils/scale";

export const rosterStyles = StyleSheet.create({
  container: { flex: 1 },
  autoButton: {
    paddingHorizontal: s(10),
    paddingVertical: s(4),
    borderRadius: 6,
  },
  autoButtonText: {
    fontSize: ms(11),
    fontWeight: "700",
  },
  infoButton: {
    padding: s(2),
  },
  shareButton: {
    padding: s(4),
  },
  scrollContent: { paddingBottom: s(56) },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: s(20),
  },
  dayNav: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: s(8),
    paddingVertical: s(10),
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  irLockBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: s(8),
    marginHorizontal: s(12),
    marginTop: s(10),
    padding: s(10),
    borderRadius: s(8),
    borderWidth: 1,
  },
  irLockBannerText: {
    flex: 1,
    fontSize: ms(13),
    lineHeight: ms(17),
  },
  navArrow: { padding: s(12) },
  navArrowText: { fontSize: ms(28), lineHeight: ms(32) },
  todayChip: {
    position: "absolute",
    top: 0,
    bottom: 0,
    justifyContent: "center",
    paddingHorizontal: s(4),
  },
  todayChipLeft: { left: s(50) },
  todayChipRight: { right: s(50) },
  dayInfo: { flex: 1, alignItems: "center" },
  dayLabel: { fontSize: ms(16) },
  daySubLabel: { fontSize: ms(11), marginTop: 2 },
  section: { padding: s(16), paddingBottom: 0 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: s(8),
  },
  totalBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: s(8),
    paddingVertical: s(3),
    borderRadius: 6,
    borderWidth: 1,
    gap: s(5),
  },
  totalLabel: { fontSize: ms(10), fontWeight: "600" },
  totalValue: {
    fontSize: ms(16),
    fontWeight: "700",
    minWidth: s(44),
    textAlign: "right",
  },
  emptyBench: { padding: s(16), alignItems: "center" },
  card: {
    borderRadius: 8,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  slotRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: s(56),
  },
  slotLabel: {
    width: s(44),
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
  },
  slotLabelText: { fontSize: ms(11), fontWeight: "700" },
  slotPlayer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: s(6),
    paddingHorizontal: s(12),
  },
  rosterPortraitWrap: {
    width: s(50),
    height: s(50),
    marginRight: s(8),
    alignItems: "center",
  },
  onCourtDot: {
    position: "absolute" as const,
    top: s(6),
    left: s(6),
    width: s(8),
    height: s(8),
    borderRadius: 4,
    zIndex: 2,
  },
  rosterHeadshotCircle: {
    width: s(48),
    height: s(48),
    borderRadius: 25,
    borderWidth: 1.5,
    overflow: "hidden" as const,
  },
  rosterHeadshotImg: {
    position: "absolute" as const,
    bottom: -2,
    left: 0,
    right: 0,
    height: s(42),
  },
  rosterTeamPill: {
    position: "absolute",
    bottom: -1,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.75)",
    borderRadius: 8,
    paddingHorizontal: s(3),
    paddingVertical: 1,
    gap: 2,
  },
  rosterTeamPillLogo: {
    width: s(9),
    height: s(9),
  },
  rosterTeamPillText: {
    fontSize: ms(7),
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  slotPlayerInfo: { flex: 1, marginRight: s(8) },
  slotLine1: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  slotLine3: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 3,
  },
  slotMatchupRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  slotPlayerName: { fontSize: ms(14), lineHeight: ms(18) },
  slotPlayerSub: { fontSize: ms(11), lineHeight: ms(15) },
  slotFpts: { fontSize: ms(13), fontWeight: "600" },
  emptySlotText: { fontSize: ms(13), fontStyle: "italic" },
  todayChipText: { fontSize: ms(11), fontWeight: "600" },
  matchupChip: {
    paddingHorizontal: s(4),
    paddingVertical: 1,
    borderRadius: 3,
  },
  matchupChipLive: {
    borderWidth: 1,
  },
  matchupChipText: {
    fontSize: ms(9),
    fontWeight: "600" as const,
  },
  liveBadge: {
    paddingHorizontal: s(4),
    paddingVertical: 1,
    borderRadius: 3,
  },
  liveText: {
    fontSize: ms(8),
    fontWeight: "800",
    letterSpacing: 0.5,
  },
});
